/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-07 06:34:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class AddExpenses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String userEmail = (String) session.getAttribute("user");
    if(userEmail == null){
        response.sendRedirect("signin.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Manage Expenses</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body{\r\n");
      out.write("        margin:0;\r\n");
      out.write("        font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("        background: linear-gradient(to right, #e0f7ff, #87ceeb);\r\n");
      out.write("    }\r\n");
      out.write("    .container{\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        max-width: 900px;\r\n");
      out.write("        margin: 30px auto;\r\n");
      out.write("        background:white;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow:0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("    }\r\n");
      out.write("    h2{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        color:#0077cc;\r\n");
      out.write("        margin-bottom:20px;\r\n");
      out.write("    }\r\n");
      out.write("    form{\r\n");
      out.write("        display:flex;\r\n");
      out.write("        gap:15px;\r\n");
      out.write("        justify-content:center;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        margin-bottom:30px;\r\n");
      out.write("    }\r\n");
      out.write("    select, input[type=number], input[type=date]{\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        border-radius:8px;\r\n");
      out.write("        border:1px solid #ccc;\r\n");
      out.write("        outline:none;\r\n");
      out.write("        width:150px;\r\n");
      out.write("    }\r\n");
      out.write("    input[type=submit]{\r\n");
      out.write("        padding:10px 20px;\r\n");
      out.write("        background:#0077cc;\r\n");
      out.write("        color:white;\r\n");
      out.write("        border:none;\r\n");
      out.write("        border-radius:8px;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("        font-weight:bold;\r\n");
      out.write("        transition:0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    input[type=submit]:hover{\r\n");
      out.write("        background:#005fa3;\r\n");
      out.write("    }\r\n");
      out.write("    table{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("    table th, table td{\r\n");
      out.write("        border:1px solid #ccc;\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("    table th{\r\n");
      out.write("        background:#0077cc;\r\n");
      out.write("        color:white;\r\n");
      out.write("    }\r\n");
      out.write("    a.button{\r\n");
      out.write("        background:#0077cc;\r\n");
      out.write("        color:white;\r\n");
      out.write("        padding:5px 12px;\r\n");
      out.write("        border-radius:8px;\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        transition:0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    a.button:hover{\r\n");
      out.write("        background:#005fa3;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h2>Manage Your Expenses</h2>\r\n");
      out.write("\r\n");
      out.write("<!-- Add Expense Form -->\r\n");
      out.write("<form method=\"post\" action=\"AddExpense.jsp\">\r\n");
      out.write("    <select name=\"category\" required>\r\n");
      out.write("        <option value=\"\">Category</option>\r\n");
      out.write("        <option value=\"Food\">Food</option>\r\n");
      out.write("        <option value=\"Travel\">Travel</option>\r\n");
      out.write("        <option value=\"Shopping\">Shopping</option>\r\n");
      out.write("        <option value=\"Bills\">Bills</option>\r\n");
      out.write("        <option value=\"Others\">Others</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <input type=\"number\" name=\"amount\" placeholder=\"Amount\" required>\r\n");
      out.write("    <input type=\"date\" name=\"date\" required>\r\n");
      out.write("    <input type=\"submit\" value=\"Add Expense\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- Existing Expenses Table -->\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>Category</th>\r\n");
      out.write("        <th>Amount (₹)</th>\r\n");
      out.write("        <th>Date</th>\r\n");
      out.write("        <th>Actions</th>\r\n");
      out.write("    </tr>\r\n");

    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/budget",
            "root",
            "yashu316378"
        );

        PreparedStatement ps = conn.prepareStatement(
            "SELECT id, category, amount, date FROM expenses WHERE email=? ORDER BY date DESC"
        );
        ps.setString(1, userEmail);
        ResultSet rs = ps.executeQuery();

        while(rs.next()){
            int id = rs.getInt("id");
            String category = rs.getString("category");
            double amount = rs.getDouble("amount");
            String date = rs.getString("date");

      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td>");
      out.print(category);
      out.write("</td>\r\n");
      out.write("        <td>₹ ");
      out.print(amount);
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(date);
      out.write("</td>\r\n");
      out.write("        <td>\r\n");
      out.write("            <a class=\"button\" href=\"EditExpenseForm.jsp?id=");
      out.print(id);
      out.write("\">Edit</a>\r\n");
      out.write("            <a class=\"button\" href=\"DeleteExpense.jsp?id=");
      out.print(id);
      out.write("\">Delete</a>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");

        }
        conn.close();
    } catch(Exception e){
        out.println("<tr><td colspan='4' style='color:red'>Error: "+e.getMessage()+"</td></tr>");
    }

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
