/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-10 13:38:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String email = (String) session.getAttribute("user");
if(email == null){
    response.sendRedirect("signin.jsp");
    return;
}

// Fetch data
String name = "";
double income = 0, savings = 0, totalExpense = 0;
double remainingBudget = 0;

// Category-wise expenses for pie chart
double food = 0, travel = 0, shopping = 0, others = 0;

// Monthly expenses for bar chart
double jan=0,feb=0,mar=0,apr=0,may=0,jun=0,jul=0,aug=0,sep=0,oct=0,nov=0,dec=0;

try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/budget","root","yashu316378");

    // User info
    PreparedStatement ps1 = con.prepareStatement("SELECT name, income, savings_target FROM user WHERE email=?");
    ps1.setString(1,email);
    ResultSet rs1 = ps1.executeQuery();
    if(rs1.next()){
        name = rs1.getString("name");
        income = rs1.getDouble("income");
        savings = rs1.getDouble("savings_target");
    } else {
        name = "User";
    }

    // Total expenses
    PreparedStatement ps2 = con.prepareStatement("SELECT SUM(amount) as total FROM expenses WHERE email=?");
    ps2.setString(1,email);
    ResultSet rs2 = ps2.executeQuery();
    if(rs2.next()){
        totalExpense = rs2.getDouble("total");
    }

    // Remaining Budget Calculation
    remainingBudget = income - totalExpense;

    // Category-wise for pie chart
    PreparedStatement ps3 = con.prepareStatement("SELECT category, SUM(amount) as total FROM expenses WHERE email=? GROUP BY category");
    ps3.setString(1,email);
    ResultSet rs3 = ps3.executeQuery();
    while(rs3.next()){
        String cat = rs3.getString("category");
        double amt = rs3.getDouble("total");
        if("Food".equals(cat)) food = amt;
        else if("Travel".equals(cat)) travel = amt;
        else if("Shopping".equals(cat)) shopping = amt;
        else others = amt;
    }

    // Monthly expenses for bar chart
    PreparedStatement ps4 = con.prepareStatement(
        "SELECT MONTH(date) as mon, SUM(amount) as total FROM expenses WHERE email=? GROUP BY MONTH(date)");
    ps4.setString(1,email);
    ResultSet rs4 = ps4.executeQuery();
    while(rs4.next()){
        int mon = rs4.getInt("mon");
        double amt = rs4.getDouble("total");
        switch(mon){
            case 1: jan=amt; break;
            case 2: feb=amt; break;
            case 3: mar=amt; break;
            case 4: apr=amt; break;
            case 5: may=amt; break;
            case 6: jun=amt; break;
            case 7: jul=amt; break;
            case 8: aug=amt; break;
            case 9: sep=amt; break;
            case 10: oct=amt; break;
            case 11: nov=amt; break;
            case 12: dec=amt; break;
        }
    }

    con.close();
}catch(Exception e){
    e.printStackTrace();
}

// Savings progress %
double savingsProgress = 0;
if(savings > 0){
    savingsProgress = ((income-totalExpense)/savings) * 100;
    if(savingsProgress > 100) savingsProgress = 100;
    if(savingsProgress<0) savingsProgress = 0;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Dashboard</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("google.charts.load('current', {'packages':['corechart','bar']});\r\n");
      out.write("google.charts.setOnLoadCallback(drawCharts);\r\n");
      out.write("\r\n");
      out.write("function drawCharts() {\r\n");
      out.write("\r\n");
      out.write("    var dataPie = google.visualization.arrayToDataTable([\r\n");
      out.write("        ['Category', 'Amount'],\r\n");
      out.write("        ['Food', ");
      out.print(food);
      out.write("],\r\n");
      out.write("        ['Travel', ");
      out.print(travel);
      out.write("],\r\n");
      out.write("        ['Shopping', ");
      out.print(shopping);
      out.write("],\r\n");
      out.write("        ['Others', ");
      out.print(others);
      out.write("]\r\n");
      out.write("    ]);\r\n");
      out.write("\r\n");
      out.write("    var optionsPie = {\r\n");
      out.write("        title: 'Expense Breakdown',\r\n");
      out.write("        pieHole: 0.4,\r\n");
      out.write("        colors: ['#ff6384', '#36a2eb', '#ffcd56', '#4bc0c0'],\r\n");
      out.write("        chartArea: {width:'90%', height:'70%'},\r\n");
      out.write("        legend: {position: 'bottom'}\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var chartPie = new google.visualization.PieChart(document.getElementById('piechart'));\r\n");
      out.write("    chartPie.draw(dataPie, optionsPie);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var dataBar = google.visualization.arrayToDataTable([\r\n");
      out.write("        ['Month', 'Expenses', { role: 'style' }],\r\n");
      out.write("        ['Jan', ");
      out.print(jan);
      out.write(", '#ff6384'],\r\n");
      out.write("        ['Feb', ");
      out.print(feb);
      out.write(", '#36a2eb'],\r\n");
      out.write("        ['Mar', ");
      out.print(mar);
      out.write(", '#ffcd56'],\r\n");
      out.write("        ['Apr', ");
      out.print(apr);
      out.write(", '#4bc0c0'],\r\n");
      out.write("        ['May', ");
      out.print(may);
      out.write(", '#ff6384'],\r\n");
      out.write("        ['Jun', ");
      out.print(jun);
      out.write(", '#36a2eb'],\r\n");
      out.write("        ['Jul', ");
      out.print(jul);
      out.write(", '#ffcd56'],\r\n");
      out.write("        ['Aug', ");
      out.print(aug);
      out.write(", '#4bc0c0'],\r\n");
      out.write("        ['Sep', ");
      out.print(sep);
      out.write(", '#ff6384'],\r\n");
      out.write("        ['Oct', ");
      out.print(oct);
      out.write(", '#36a2eb'],\r\n");
      out.write("        ['Nov', ");
      out.print(nov);
      out.write(", '#ffcd56'],\r\n");
      out.write("        ['Dec', ");
      out.print(dec);
      out.write(", '#4bc0c0']\r\n");
      out.write("    ]);\r\n");
      out.write("\r\n");
      out.write("    var optionsBar = {\r\n");
      out.write("        title: 'Monthly Expenses',\r\n");
      out.write("        legend: { position: 'none' },\r\n");
      out.write("        chartArea: {width:'80%', height:'70%'},\r\n");
      out.write("        hAxis: {title: 'Month'},\r\n");
      out.write("        vAxis: {title: 'Amount (₹)'}\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var chartBar = new google.visualization.ColumnChart(document.getElementById('barchart'));\r\n");
      out.write("    chartBar.draw(dataBar, optionsBar);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    background: linear-gradient(to right, #87ceeb, #e0f7ff);\r\n");
      out.write("}\r\n");
      out.write(".dashboard{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    height:100vh;\r\n");
      out.write("}\r\n");
      out.write(".sidebar{\r\n");
      out.write("    width:220px;\r\n");
      out.write("    background:#0077cc;\r\n");
      out.write("    color:white;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("}\r\n");
      out.write(".sidebar h3{ margin-bottom:20px; }\r\n");
      out.write(".sidebar a{\r\n");
      out.write("    display:block;\r\n");
      out.write("    color:white;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("    margin-bottom:10px;\r\n");
      out.write("}\r\n");
      out.write(".sidebar a:hover{ background:#005fa3; }\r\n");
      out.write(".main{\r\n");
      out.write("    flex:1;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("    background:white;\r\n");
      out.write("    padding:15px;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("    box-shadow:0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("    margin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write(".cards{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    gap:20px;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("    margin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write(".card{\r\n");
      out.write("    background:white;\r\n");
      out.write("    width:180px;\r\n");
      out.write("    height:100px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow:0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    transition:0.3s;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".card:hover{\r\n");
      out.write("    transform:translateY(-5px);\r\n");
      out.write("    background:#e6f2ff;\r\n");
      out.write("}\r\n");
      out.write("#piechart, #barchart{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 500px;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    margin: 0 auto 20px auto;\r\n");
      out.write("}\r\n");
      out.write(".progress-bar-container{\r\n");
      out.write("    background:#e0f7ff;\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    margin:10px 0 20px 0;\r\n");
      out.write("}\r\n");
      out.write(".progress-bar{\r\n");
      out.write("    height:25px;\r\n");
      out.write("    line-height:25px;\r\n");
      out.write("    color:white;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("<h3>Menu</h3>\r\n");
      out.write("<a href=\"ProfilePage.jsp\">Profile</a>\r\n");
      out.write("<a href=\"ManageExpense.jsp\">Manage Expenses</a>\r\n");
      out.write("<a href=\"TrackExpenses.jsp\">Track Expenses</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("<h2>Welcome, ");
      out.print(name);
      out.write("!</h2>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Income: ₹");
      out.print(income);
      out.write(" |\r\n");
      out.write("Savings Target: ₹");
      out.print(savings);
      out.write(" |\r\n");
      out.write("Expenses: ₹");
      out.print(totalExpense);
      out.write(" |\r\n");
      out.write("Remaining Budget: ₹");
      out.print(remainingBudget);
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");

if(remainingBudget < 0){

      out.write("\r\n");
      out.write("<p style=\"color:red; font-weight:bold;\">\r\n");
      out.write("⚠ Warning: Your expenses exceeded your income!\r\n");
      out.write("</p>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>Savings Goal Progress</h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"progress-bar-container\">\r\n");
      out.write("<div class=\"progress-bar\" style=\"width:");
      out.print( (int)savingsProgress );
      out.write("%;\r\n");
      out.write("background: linear-gradient(90deg,#ff6384,#36a2eb,#ffcd56,#4bc0c0);\">\r\n");
      out.print( (int)savingsProgress );
      out.write("%\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"cards\">\r\n");
      out.write("<a href=\"ManageExpense.jsp\"><div class=\"card\">Add Expense</div></a>\r\n");
      out.write("<a href=\"ViewExpense.jsp\"><div class=\"card\">View Expenses</div></a>\r\n");
      out.write("<a href=\"ProfilePage.jsp\"><div class=\"card\">Update Profile</div></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"piechart\"></div>\r\n");
      out.write("<div id=\"barchart\"></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
