/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-10 08:05:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class ManageExpense_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String user = (String) session.getAttribute("user");
    if(user == null){
        response.sendRedirect("signin.jsp");
        return;
    }

    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/budget", "root", "yashu316378");

    // Handle Add / Update
    String idParam = request.getParameter("id");
    String categoryParam = request.getParameter("category");
    String amountParam = request.getParameter("amount");
    String dateParam = request.getParameter("date");

    if(categoryParam != null && amountParam != null && dateParam != null){
        if(idParam == null || idParam.isEmpty()){
            // Add new expense
            PreparedStatement ps = conn.prepareStatement("INSERT INTO expenses(email, category, amount, date) VALUES(?,?,?,?)");
            ps.setString(1, user);
            ps.setString(2, categoryParam);
            ps.setDouble(3, Double.parseDouble(amountParam));
            ps.setString(4, dateParam);
            ps.executeUpdate();
            ps.close();
        } else {
            // Update existing expense
            PreparedStatement ps = conn.prepareStatement("UPDATE expenses SET category=?, amount=?, date=? WHERE id=? AND email=?");
            ps.setString(1, categoryParam);
            ps.setDouble(2, Double.parseDouble(amountParam));
            ps.setString(3, dateParam);
            ps.setInt(4, Integer.parseInt(idParam));
            ps.setString(5, user);
            ps.executeUpdate();
            ps.close();
        }
        response.sendRedirect("ManageExpenses.jsp");
        return;
    }

    // Handle Delete
    String deleteId = request.getParameter("deleteId");
    if(deleteId != null){
        PreparedStatement ps = conn.prepareStatement("DELETE FROM expenses WHERE id=? AND email=?");
        ps.setInt(1, Integer.parseInt(deleteId));
        ps.setString(2, user);
        ps.executeUpdate();
        ps.close();
        response.sendRedirect("ManageExpenses.jsp");
        return;
    }

    // Handle Edit
    String editId = request.getParameter("editId");
    String editCategory = "";
    String editAmount = "";
    String editDate = "";
    if(editId != null){
        PreparedStatement ps = conn.prepareStatement("SELECT * FROM expenses WHERE id=? AND email=?");
        ps.setInt(1, Integer.parseInt(editId));
        ps.setString(2, user);
        ResultSet rsEdit = ps.executeQuery();
        if(rsEdit.next()){
            editCategory = rsEdit.getString("category");
            editAmount = String.valueOf(rsEdit.getDouble("amount"));
            editDate = rsEdit.getString("date");
        }
        rsEdit.close();
        ps.close();
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Manage Expenses</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("            background: linear-gradient(to right, #87ceeb, #e0f7ff);\r\n");
      out.write("            margin: 0; padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 750px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        h2 { color: #0077cc; text-align: center; }\r\n");
      out.write("        input, select, button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin: 8px 0;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background: #0077cc; color: white; border: none; font-weight: bold; cursor: pointer; transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover { background: #005fa3; }\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 25px; }\r\n");
      out.write("        table, th, td { border: 1px solid #ccc; }\r\n");
      out.write("        th, td { padding: 10px; text-align: center; }\r\n");
      out.write("        th { background-color: #0077cc; color: white; }\r\n");
      out.write("        .action-btn { width: auto; padding: 5px 10px; }\r\n");
      out.write("        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <h2>Manage Expenses</h2>\r\n");
      out.write("        <p>Welcome, <b>");
      out.print( user );
      out.write("</b></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Add / Update Form -->\r\n");
      out.write("    <form method=\"post\" action=\"ManageExpense.jsp\">\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( editId != null ? editId : "" );
      out.write("\">\r\n");
      out.write("        <select name=\"category\" required>\r\n");
      out.write("            <option value=\"\">Select Category</option>\r\n");
      out.write("            <option value=\"Food\" ");
      out.print( "Food".equals(editCategory) ? "selected" : "" );
      out.write(">Food</option>\r\n");
      out.write("            <option value=\"Travel\" ");
      out.print( "Travel".equals(editCategory) ? "selected" : "" );
      out.write(">Travel</option>\r\n");
      out.write("            <option value=\"Shopping\" ");
      out.print( "Shopping".equals(editCategory) ? "selected" : "" );
      out.write(">Shopping</option>\r\n");
      out.write("            <option value=\"Others\" ");
      out.print( "Others".equals(editCategory) ? "selected" : "" );
      out.write(">Others</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <input type=\"number\" name=\"amount\" placeholder=\"Amount\" value=\"");
      out.print( editAmount );
      out.write("\" required>\r\n");
      out.write("        <input type=\"date\" name=\"date\" value=\"");
      out.print( editDate );
      out.write("\" required>\r\n");
      out.write("        <button type=\"submit\">");
      out.print( editId != null ? "Update Expense" : "Add Expense" );
      out.write("</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- List of Expenses -->\r\n");
      out.write("    <h3>Your Expenses</h3>\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Category</th>\r\n");
      out.write("            <th>Amount</th>\r\n");
      out.write("            <th>Date</th>\r\n");
      out.write("            <th>Actions</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

            PreparedStatement psList = conn.prepareStatement("SELECT * FROM expenses WHERE email=? ORDER BY date DESC");
            psList.setString(1, user);
            ResultSet rs = psList.executeQuery();
            while(rs.next()){
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( rs.getString("category") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getDouble("amount") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getDate("date") );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <a href=\"ManageExpense.jsp?editId=");
      out.print( rs.getInt("id") );
      out.write("\"><button type=\"button\" class=\"action-btn\">Edit</button></a>\r\n");
      out.write("                <a href=\"ManageExpense.jsp?deleteId=");
      out.print( rs.getInt("id") );
      out.write("\" onclick=\"return confirm('Delete this expense?');\">\r\n");
      out.write("                    <button type=\"button\" class=\"action-btn\">Delete</button>\r\n");
      out.write("                </a>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } rs.close(); psList.close(); conn.close(); 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
