/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-10 07:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.Map;
import java.util.LinkedHashMap;

public final class TrackExpenses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.LinkedHashMap");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// Check if user is logged in
String email = (String) session.getAttribute("user");
if(email == null){
response.sendRedirect("signin.jsp");
return;
}

// Fetch user data
String name = "";
double income = 0, savingsTarget = 0, totalExpense = 0, remainingBudget = 0;
Map<String, Double> categoryExpenses = new LinkedHashMap<>(); // for charts

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/budget","root","yashu316378");

    // User info
    PreparedStatement psUser = con.prepareStatement("SELECT name, income, savings_target FROM user WHERE email=?");
    psUser.setString(1,email);
    ResultSet rsUser = psUser.executeQuery();
    if(rsUser.next()){
        name = rsUser.getString("name");
        income = rsUser.getDouble("income");
        savingsTarget = rsUser.getDouble("savings_target");
    }
    rsUser.close();
    psUser.close();

    // Total expenses
    PreparedStatement psTotal = con.prepareStatement("SELECT SUM(amount) as total FROM expenses WHERE email=?");
    psTotal.setString(1,email);
    ResultSet rsTotal = psTotal.executeQuery();
    if(rsTotal.next()){
        totalExpense = rsTotal.getDouble("total");
    }
    rsTotal.close();
    psTotal.close();

    // Remaining Budget calculation
    remainingBudget = income - totalExpense;

    // Expenses by category
    PreparedStatement psCat = con.prepareStatement(
        "SELECT category, SUM(amount) as total FROM expenses WHERE email=? GROUP BY category"
    );
    psCat.setString(1,email);
    ResultSet rsCat = psCat.executeQuery();
    while(rsCat.next()){
        categoryExpenses.put(rsCat.getString("category"), rsCat.getDouble("total"));
    }
    rsCat.close();
    psCat.close();

    con.close();
} catch(Exception e){
    e.printStackTrace();
}

// Prepare data for Chart.js
StringBuilder catLabels = new StringBuilder();
StringBuilder catData = new StringBuilder();
for(Map.Entry<String, Double> entry : categoryExpenses.entrySet()){
    if(catLabels.length() > 0){
        catLabels.append(",");
        catData.append(",");
    }
    catLabels.append("'").append(entry.getKey()).append("'");
    catData.append(entry.getValue());
}

// ===== Savings progress based on income and savings target =====
double savingsProgress = 0;
if(savingsTarget > 0){
    savingsProgress = ((income - totalExpense) / savingsTarget) * 100;
    if(savingsProgress > 100) savingsProgress = 100;
    if(savingsProgress < 0) savingsProgress = 0;
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html><html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Track Expenses</title>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    background: linear-gradient(to right, #87ceeb, #e0f7ff);\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("    max-width:900px;\r\n");
      out.write("    margin:40px auto;\r\n");
      out.write("    background:white;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    border-radius:15px;\r\n");
      out.write("    box-shadow:0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write("h2, h3{color:#0077cc; text-align:center;}\r\n");
      out.write(".chart-container{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content:space-around;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("    gap:30px;\r\n");
      out.write("    margin-top:30px;\r\n");
      out.write("}\r\n");
      out.write(".chart-box{\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    background:#f2f9ff;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow:0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write(".progress-bar-container{\r\n");
      out.write("    background:#e0f7ff;\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    margin:20px 0;\r\n");
      out.write("}\r\n");
      out.write(".progress-bar{\r\n");
      out.write("    height:25px;\r\n");
      out.write("    line-height:25px;\r\n");
      out.write("    color:white;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\"><h2>Welcome, ");
      out.print(name);
      out.write("!</h2><p style=\"text-align:center;\">\r\n");
      out.write("Income: ₹");
      out.print(income);
      out.write(" | \r\n");
      out.write("Savings Target: ₹");
      out.print(savingsTarget);
      out.write(" | \r\n");
      out.write("Total Expenses: ₹");
      out.print(totalExpense);
      out.write(" | \r\n");
      out.write("Remaining Budget: ₹");
      out.print(remainingBudget);
      out.write("\r\n");
      out.write("</p><h3>Savings Goal Progress</h3>\r\n");
      out.write("<div class=\"progress-bar-container\">\r\n");
      out.write("    <div class=\"progress-bar\" style=\"width:");
      out.print( (int)savingsProgress );
      out.write("%;\r\n");
      out.write("         background: linear-gradient(90deg,#ff6384,#36a2eb,#ffcd56,#4bc0c0);\">\r\n");
      out.write("        ");
      out.print( (int)savingsProgress );
      out.write("%\r\n");
      out.write("    </div>\r\n");
      out.write("</div><div class=\"chart-container\">\r\n");
      out.write("    <div class=\"chart-box\">\r\n");
      out.write("        <h3>Expenses by Category (Pie Chart)</h3>\r\n");
      out.write("        <canvas id=\"pieChart\"></canvas>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"chart-box\">\r\n");
      out.write("        <h3>Expenses by Category (Bar Chart)</h3>\r\n");
      out.write("        <canvas id=\"barChart\"></canvas>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><script>\r\n");
      out.write("const pieCtx = document.getElementById('pieChart').getContext('2d');\r\n");
      out.write("const pieChart = new Chart(pieCtx, {\r\n");
      out.write("    type: 'pie',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [");
      out.print(catLabels.toString());
      out.write("],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            data: [");
      out.print(catData.toString());
      out.write("],\r\n");
      out.write("            backgroundColor: [\r\n");
      out.write("                '#0077cc','#00aaff','#87ceeb','#cce6ff','#99ccff','#66b2ff'\r\n");
      out.write("            ]\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write("    options: {\r\n");
      out.write("        responsive:true,\r\n");
      out.write("        plugins:{\r\n");
      out.write("            legend:{ position:'bottom' }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("const barCtx = document.getElementById('barChart').getContext('2d');\r\n");
      out.write("const barChart = new Chart(barCtx, {\r\n");
      out.write("    type: 'bar',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: [");
      out.print(catLabels.toString());
      out.write("],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            label: 'Expenses ₹',\r\n");
      out.write("            data: [");
      out.print(catData.toString());
      out.write("],\r\n");
      out.write("            backgroundColor: [\r\n");
      out.write("                '#0077cc','#00aaff','#87ceeb','#cce6ff','#99ccff','#66b2ff'\r\n");
      out.write("            ]\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write("    options:{\r\n");
      out.write("        responsive:true,\r\n");
      out.write("        scales:{\r\n");
      out.write("            y:{ beginAtZero:true }\r\n");
      out.write("        },\r\n");
      out.write("        plugins:{\r\n");
      out.write("            legend:{ display:false }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script></body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
